version: '3'
services:
  python_dev_env:
    restart: always
    build:
      context: ./dockerfiles
      dockerfile: dockerfile
      args:
        - USER=${USER}
        - GID=${GID}
        - UID=${UID}
    container_name: 'python_dev_env'
    working_dir: '/home/$USER/workspace'
    tty: true
    volumes:
      - ./share:/home/$USER/workspace

